/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuy_tinker_NativeJni */

#ifndef _Included_com_liuy_tinker_NativeJni
#define _Included_com_liuy_tinker_NativeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuy_tinker_NativeJni
 * Method:    toStringforJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liuy_tinker_NativeJni_toStringforJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
